# Generated by Django 5.0 on 2023-12-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
    ]
