# Generated by Django 5.0 on 2023-12-30 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_remove_chatmessage_is_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='content',
        ),
    ]
