# Generated by Django 5.0 on 2024-01-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatmessage_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='group_name',
            field=models.CharField(default='group', max_length=256),
        ),
    ]
